# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build Docker image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

- stage: Staging
  displayName: Deploy to Staging
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: Deploy to Staging environment
    pool:
      vmImage: ubuntu-latest
    steps:
   
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: 'DockerHubConnection'

    
    - task: Docker@2
      displayName: Push image to Docker Hub
      inputs:
        command: push
        tags: |
          $(tag)
    - script: |
        docker run -d --name my-app-staging -p 8080:80 my-app:$(tag)
      displayName: Run container in Staging
